### ISSUE TITLE
How to provide user services after payment has been received

### ISSUE THREAD

**Issue by nonew** [hifocus/merger#22]
Dear developer,

I want user download file or view special content from my website only after their payment is made.
I went through the merger documents, but did not find articles related to this topic.

Could you help to explain how to implement this feature by merger? Thanks!

**Comment by hifocus** [comment]
If you are trying to integrate a paywall-like function, merger is the wrong place to go.

As repeatedly mentioned to others, merger relies on personal payment QR Code only, instead of merchant QR Codes, which can be used for integrate said function.

It's currently impossible (or extremely difficult) for personal payment QR Codes to be used as merchant ones, as they do not provide APIs. So all in all, merger is for QR Codes presentations only if you like; it is just a graphical interface, which doesn't provide any advanced functionalities.

Thanks for your attention.
